version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 387283381312.dkr.ecr.ca-central-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t koti-ecs-app .
      - docker tag koti-ecs-app:latest 387283381312.dkr.ecr.ca-central-1.amazonaws.com/koti-ecs-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 387283381312.dkr.ecr.ca-central-1.amazonaws.com/koti-ecs-app:latest
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"koti-container","imageUri":"387283381312.dkr.ecr.ca-central-1.amazonaws.com/koti-ecs-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
